### ISSUE TITLE
Error: CanvasPlus: Image has invalid dimensions when using a mask

### ISSUE THREAD

**Issue by tiavina-mika** [jhuckaby/canvas-plus#12]
I've got an "Error: CanvasPlus: Image has invalid dimensions" error when using canvas.mask

```
err:  Error: CanvasPlus: Image has invalid dimensions
    at __construct.doError (E:\iota\server\node_modules\pixl-canvas-plus\main.js:571:13)
    at __construct.composite (E:\iota\server\node_modules\pixl-canvas-plus\lib\filter\composite.js:63:16)    
    at __construct.mask (E:\iota\server\node_modules\pixl-canvas-plus\lib\filter\composite.js:114:15)        
    at generateImage (E:\iota\server\cloud\hooks\montages.js:469:14)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createNewCanvas (E:\iota\server\cloud\hooks\montages.js:585:22)
    at async E:\iota\server\index.js:267:19 {
  code: 'composite',
  component: 'CanvasPlus'
}
```

here is my code:
```
try {
      const image = 'https://storage.googleapis.com/template-preprod-ojhfeisoax/template-preprod-ojhfeisoax_6dacb23c641f7dcf00b61f82be7218e1_zem5rcqm8v.jpeg';
      const mask =  'https://lh3.googleusercontent.com/proxy/GXT42IxIKE5eJPlywP8Lm3ULh0e3wrHWi57y1X8wtA8hihjxrfrkI6zs_tJ37OPPJiHXCVnDGDnZOjrvdQgSdkg2LE9u5oNhGZbQvm2J_nMEFBNNT5E';
      
      await canvas.load(image);
      canvas.resize({
        width: 1000,
        height: 500,
        mode: 'fitover',
      });
      canvas.mask({
        image: mask,
      });

      // --------------------------------------------------------------- //
      // ------------------------- result file ------------------------- //
      // --------------------------------------------------------------- //
      const buffer = await canvas.write({ "format":"png" });
      const raw = Buffer.from(buffer).toString('base64');
      let dataUrl =  'data:image/png;base64,' + raw;

      return dataUrl;
    } catch (error) {
      console.log(error);
    }
```

**Comment by tiavina-mika** [comment]
Solved!
I transformed the mask to another canvas

```
	const canvas2 = new CanvasPlus();
	const canvas3 = new CanvasPlus();

	await canvas3.load(imageMask);
	canvas2.mask({
		image: canvas3,
	});

	canvas.composite({
		image: canvas2,
		width: childLayer.width,
		height: childLayer.height,
		gravity: 'west',
		offsetX: childLayer.left,
		offsetY: childLayer.top,
	});
```
